// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gui} from '../models';

export function CancelTransfer():Promise<void>;

export function ConnectToReceive(arg1:string):Promise<void>;

export function GetDeviceInfo():Promise<gui.DeviceInfo>;

export function GetFileInfo(arg1:string):Promise<gui.FileInfo>;

export function GetSenderPort():Promise<number>;

export function GetSettings():Promise<gui.Settings>;

export function GetTransferHistory():Promise<Array<gui.HistoryEntry>>;

export function IsSending():Promise<boolean>;

export function SaveSettings(arg1:gui.Settings):Promise<void>;

export function ScanPeers():Promise<Array<gui.PeerInfo>>;

export function SelectDownloadDir():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function StartSending(arg1:string):Promise<void>;

export function StopSending():Promise<void>;
