// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTransfer() {
  return window['go']['gui']['App']['CancelTransfer']();
}

export function ConnectToReceive(arg1) {
  return window['go']['gui']['App']['ConnectToReceive'](arg1);
}

export function GetDeviceInfo() {
  return window['go']['gui']['App']['GetDeviceInfo']();
}

export function GetFileInfo(arg1) {
  return window['go']['gui']['App']['GetFileInfo'](arg1);
}

export function GetSenderPort() {
  return window['go']['gui']['App']['GetSenderPort']();
}

export function GetSettings() {
  return window['go']['gui']['App']['GetSettings']();
}

export function GetTransferHistory() {
  return window['go']['gui']['App']['GetTransferHistory']();
}

export function IsSending() {
  return window['go']['gui']['App']['IsSending']();
}

export function SaveSettings(arg1) {
  return window['go']['gui']['App']['SaveSettings'](arg1);
}

export function ScanPeers() {
  return window['go']['gui']['App']['ScanPeers']();
}

export function SelectDownloadDir() {
  return window['go']['gui']['App']['SelectDownloadDir']();
}

export function SelectFiles() {
  return window['go']['gui']['App']['SelectFiles']();
}

export function SelectFolder() {
  return window['go']['gui']['App']['SelectFolder']();
}

export function StartSending(arg1) {
  return window['go']['gui']['App']['StartSending'](arg1);
}

export function StopSending() {
  return window['go']['gui']['App']['StopSending']();
}
